version: '3.8'

services:
  streamlit_resume_screener:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8123:8123"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app

